import asyncio
import subprocess
from collections.abc import Iterator
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

from app.config import Settings, get_settings
from app.db import Database, get_session
from app.main import app


def _generate_audio(path: Path, codec_args: list[str], container_args: list[str]) -> None:
    command = [
        "ffmpeg",
        "-nostdin",
        "-hide_banner",
        "-loglevel",
        "error",
        "-y",
        "-f",
        "lavfi",
        "-i",
        "sine=frequency=440:duration=2",
        *codec_args,
        *container_args,
        str(path),
    ]
    subprocess.run(command, check=True, capture_output=True, text=True)


@pytest.fixture(scope="session")
def audio_samples(tmp_path_factory: pytest.TempPathFactory) -> dict[str, Path]:
    """Deterministic 2 second audio generated by the container's own ffmpeg."""
    directory = tmp_path_factory.mktemp("audio-samples")

    webm_opus = directory / "sample.webm"
    _generate_audio(
        webm_opus,
        ["-c:a", "libopus", "-b:a", "64k", "-ac", "1"],
        ["-f", "webm"],
    )

    mp4_aac = directory / "sample.mp4"
    _generate_audio(
        mp4_aac,
        ["-c:a", "aac", "-b:a", "64k", "-ac", "1"],
        ["-f", "mp4"],
    )

    return {"webm": webm_opus, "mp4": mp4_aac}


@pytest.fixture
def meetings_dir(tmp_path: Path) -> Path:
    directory = tmp_path / "meetings"
    directory.mkdir()
    return directory


@pytest.fixture
def database(tmp_path: Path) -> Iterator[Database]:
    """Isolated SQLite database per test (never the runtime database)."""
    db = Database(f"sqlite+aiosqlite:///{tmp_path / 'test.db'}")
    asyncio.run(db.init())
    yield db
    asyncio.run(db.dispose())


@pytest.fixture
def client(meetings_dir: Path, database: Database) -> Iterator[TestClient]:
    settings = Settings(data_dir=meetings_dir, database_url=database.url)
    app.dependency_overrides[get_settings] = lambda: settings

    async def override_session():
        async for session in database.sessions():
            yield session

    app.dependency_overrides[get_session] = override_session
    # No context manager: the lifespan must not touch the runtime database.
    yield TestClient(app)
    app.dependency_overrides.clear()


def upload(
    client: TestClient,
    content: bytes,
    *,
    mime_type: str = "audio/webm;codecs=opus",
    filename: str = "recording.webm",
    content_type: str | None = None,
):
    return client.post(
        "/api/recordings",
        files={"audio": (filename, content, content_type or mime_type)},
        data={"mime_type": mime_type, "client_duration_seconds": "2.0"},
    )
